# Generated by Django 2.2.28 on 2022-09-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.AccountUser')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountUser')),
            ],
        ),
    ]
