# Generated by Django 2.2.28 on 2022-09-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.AccountUser')),
                ('following', models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.AccountUser')),
            ],
        ),
    ]
