# Generated by Django 2.2.28 on 2022-09-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelation',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_followrelation_following_+', to='follow.FollowRelation'),
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountUser'),
        ),
    ]
