# Generated by Django 2.2.28 on 2022-09-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20220914_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelation',
            name='id',
        ),
        migrations.AlterField(
            model_name='followrelation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.AccountUser'),
        ),
    ]
