# Generated by Django 2.2.28 on 2022-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20220914_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelation',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='accounts.AccountUser'),
        ),
    ]
