# Generated by Django 2.2.28 on 2022-09-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220914_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='password',
        ),
    ]
