# Generated by Django 2.2.28 on 2022-09-13 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0002_appcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='本文')),
                ('link', models.CharField(max_length=200, verbose_name='会議URL')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='accounts.AccountUser')),
            ],
        ),
        migrations.CreateModel(
            name='AppSeminarParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppSeminar')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountUser')),
            ],
        ),
    ]
