# Generated by Django 2.2.28 on 2022-09-14 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appseminar_appseminarparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appcomment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appcomment',
            name='posted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Post'),
        ),
    ]
