# Generated by Django 2.2.28 on 2022-09-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220914_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcomment',
            name='posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Post'),
        ),
    ]
